# 03: Tensors

- A specific type of array is requried in the context of PyTorch based neural nets, called "tensors"
- Tensors are similar to NumPy arrays but additional specific functionalities needed for deep learning
- Brief exploration of PyTorch tensors, accessible from the torch module:


In [1]:
import torch
import numpy as np

# import matplotlib.pyplot as plt

In [2]:
torch.cuda.is_available()

True

### Creating arrays

In [3]:
# create array filled with ones
t_array = torch.ones((3, 2))
t_array

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [4]:
n_array = np.ones((3, 2))
n_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
# find the array type with *dtype*

print(f"t_array dtype: {t_array.dtype}")
print(f"n_array type: {n_array.dtype}")

t_array dtype: torch.float32
n_array type: float64


In [6]:
# pytorch implements other funcs to create arrays similar to Numpy
# eg. random number arrays:

t_random = torch.randint(0, 255, (10, 10))
t_random

tensor([[227, 143, 247, 171, 222,  29, 239,  53, 197, 102],
        [ 94,  21,  78, 128, 162,  58, 235, 178,  49,  15],
        [179,  27, 141,   5, 103,  76, 171,  92,  52, 215],
        [212,   3, 116, 172, 193,  84, 236,  48,  77,  49],
        [147, 168,  12, 220, 212,  53, 118, 166,  55,  44],
        [235, 154,  25,  91, 145, 110,  53, 107,  97, 136],
        [205, 104,  74,  98,  14,  96, 109, 182, 197, 159],
        [ 29, 145, 105,  77, 155,  23, 124, 179, 142, 247],
        [114, 224,  53,  35,  16, 252, 111,  74, 164,  32],
        [125, 177,  91, 188, 167, 172,  22,  91,  42,  96]])

In [7]:
# from numpy to tensor
t_from_n = torch.tensor(n_array)
t_from_n

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [8]:
# numpy from tensor

t_from_n.numpy()

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
plt.imshow(t_random);

NameError: name 'plt' is not defined

### Indexing, broadcasting, etc

In [11]:
t_random

tensor([[227, 143, 247, 171, 222,  29, 239,  53, 197, 102],
        [ 94,  21,  78, 128, 162,  58, 235, 178,  49,  15],
        [179,  27, 141,   5, 103,  76, 171,  92,  52, 215],
        [212,   3, 116, 172, 193,  84, 236,  48,  77,  49],
        [147, 168,  12, 220, 212,  53, 118, 166,  55,  44],
        [235, 154,  25,  91, 145, 110,  53, 107,  97, 136],
        [205, 104,  74,  98,  14,  96, 109, 182, 197, 159],
        [ 29, 145, 105,  77, 155,  23, 124, 179, 142, 247],
        [114, 224,  53,  35,  16, 252, 111,  74, 164,  32],
        [125, 177,  91, 188, 167, 172,  22,  91,  42,  96]])

In [12]:
t_random[0, :]  # row 0

tensor([227, 143, 247, 171, 222,  29, 239,  53, 197, 102])

In [13]:
# broadcasting allows the combining of tensors of different but compatible shapes:
torch.ones((3, 5)) * torch.randint(0, 255, (1, 5))

tensor([[143., 109.,  53., 174.,   7.],
        [143., 109.,  53., 174.,   7.],
        [143., 109.,  53., 174.,   7.]])

- may need to flatten arrays
- eg. to create a fully connected layer in a deep learning network
- done in two ways:

In [14]:
t_random.flatten()

tensor([227, 143, 247, 171, 222,  29, 239,  53, 197, 102,  94,  21,  78, 128,
        162,  58, 235, 178,  49,  15, 179,  27, 141,   5, 103,  76, 171,  92,
         52, 215, 212,   3, 116, 172, 193,  84, 236,  48,  77,  49, 147, 168,
         12, 220, 212,  53, 118, 166,  55,  44, 235, 154,  25,  91, 145, 110,
         53, 107,  97, 136, 205, 104,  74,  98,  14,  96, 109, 182, 197, 159,
         29, 145, 105,  77, 155,  23, 124, 179, 142, 247, 114, 224,  53,  35,
         16, 252, 111,  74, 164,  32, 125, 177,  91, 188, 167, 172,  22,  91,
         42,  96])

Specify which contiguous dimensions you want to flatten:

In [15]:
t_3d = torch.randint(0, 100, (2, 3, 4))
t_3d

tensor([[[41, 17, 11, 35],
         [23, 32, 91, 81],
         [97,  5, 38,  7]],

        [[15, 71, 80, 60],
         [86, 62, 65, 40],
         [85, 39, 61, 81]]])

In [16]:
torch.flatten(t_3d, start_dim=1, end_dim=2)

tensor([[41, 17, 11, 35, 23, 32, 91, 81, 97,  5, 38,  7],
        [15, 71, 80, 60, 86, 62, 65, 40, 85, 39, 61, 81]])

Alternative: 

- use the *view* method, which if possible, returns only a *view* of the array
- can pass compatible dimensions to reshape the tensor, or simply use *-1* to completely flatten it

In [17]:
t_random = torch.randint(0, 255, (10, 10))

In [18]:
t_random.view(5, 20)

tensor([[ 55, 108, 202, 173, 233,  94,  13, 164, 125, 187,  83, 133,  61,  14,
          60, 140, 231,  50, 111, 155],
        [213, 160,  49,  27, 231,  63,  90, 211,  18, 199, 202, 211, 190, 234,
          20, 170,  52, 129,  26,  82],
        [175, 103, 161, 248,  86,  90, 206,  20,  14, 176, 183,  67, 172,   5,
          49,  23, 244,  22, 144, 170],
        [215,  69, 106,  86, 139,  97,  63, 237,  45, 145,  49, 160,  89,   7,
         125, 137,  93, 133,  56, 145],
        [169,  96,  31, 231, 134,  96,  88,  70,  91, 108, 223,  66,  28, 230,
          91, 152,  35,  73, 101, 167]])

In [19]:
# flatten
t_random.view(-1)

tensor([ 55, 108, 202, 173, 233,  94,  13, 164, 125, 187,  83, 133,  61,  14,
         60, 140, 231,  50, 111, 155, 213, 160,  49,  27, 231,  63,  90, 211,
         18, 199, 202, 211, 190, 234,  20, 170,  52, 129,  26,  82, 175, 103,
        161, 248,  86,  90, 206,  20,  14, 176, 183,  67, 172,   5,  49,  23,
        244,  22, 144, 170, 215,  69, 106,  86, 139,  97,  63, 237,  45, 145,
         49, 160,  89,   7, 125, 137,  93, 133,  56, 145, 169,  96,  31, 231,
        134,  96,  88,  70,  91, 108, 223,  66,  28, 230,  91, 152,  35,  73,
        101, 167])

As we are dealing with a *view*: If we modify one of the arrays *in place*, the values in the other arrays are changed as well. This means that this is **not** an independent array, but a shallow-copy. BE CAREFUL

In [20]:
view_copy = t_random.view(5, 20)
view_copy

tensor([[ 55, 108, 202, 173, 233,  94,  13, 164, 125, 187,  83, 133,  61,  14,
          60, 140, 231,  50, 111, 155],
        [213, 160,  49,  27, 231,  63,  90, 211,  18, 199, 202, 211, 190, 234,
          20, 170,  52, 129,  26,  82],
        [175, 103, 161, 248,  86,  90, 206,  20,  14, 176, 183,  67, 172,   5,
          49,  23, 244,  22, 144, 170],
        [215,  69, 106,  86, 139,  97,  63, 237,  45, 145,  49, 160,  89,   7,
         125, 137,  93, 133,  56, 145],
        [169,  96,  31, 231, 134,  96,  88,  70,  91, 108, 223,  66,  28, 230,
          91, 152,  35,  73, 101, 167]])

In [21]:
view_copy.fill_(1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
# original affected
t_random

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### Gradients

- to perform backpropogation in Deep Learning networks, we need to calculate all the necessary gradients.
- this feature is integrated into PyTorch arrays directly:
    - use the **require_grad** option
    - simple example, define a variable **x = 1**


In [23]:
x = torch.ones(1, 1, requires_grad=True)

In [24]:
x

tensor([[1.]], requires_grad=True)

Pass variable through a few simple operations:

In [25]:
y = 2 * x

In [26]:
z = y ** (3 / 2)

In [27]:
w = 5 * z

Our last variable that depended initially on x, is now w. So w needs to be optimised in respect to variable x. We can do this simply by calculating the gradients of w **dw/dx**

In [28]:
w.backward()

In [29]:
print(x.grad)

tensor([[21.2132]])


Verify that we indeed obtain the correct gradient:

In [30]:
5 * (3 / 2) * (2**0.5) * 2

21.213203435596427

recover a numpy array from a PyTorch tensor or plot a PyTorch tensor with Matplotlib

In [31]:
x.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [32]:
x.detach().numpy()

array([[1.]], dtype=float32)

### Sending tensors to a GPU

If pc has a compatible GPU, or if you run the notebook on Google Colab with a GPU runtime -> you can exploit Graphics card computing power

The data will have to be "pushed" or "pulled" to and from that device. Can push entire networks but for the moment just send a tensor

Check GPU is a available

In [3]:
torch.cuda.is_available()

True

Send the data the the "CUDA" device:

In [4]:
dev = torch.device("cuda")
dev

device(type='cuda')

In [36]:
mytensor = torch.randn((3, 5))
mytensor = mytensor.to(dev)
mytensor

tensor([[-1.1092, -0.7593, -1.3767,  0.4996,  0.7173],
        [ 0.1082,  1.4408,  1.4879, -0.1904, -0.9103],
        [-1.3160,  0.9041,  0.0470,  0.6126, -0.8336]], device='cuda:0')

Error below: We see here that we have again difficulties getting the tensor "out" of PyTorch. This time not because it's part of a gradient but because it lives on the GPU. So we need to first copy it back to the CPU first:

In [37]:
mytensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [38]:
mytensor_CPU = mytensor.cpu()

In [39]:
mytensor_CPU.numpy()

array([[-1.1092274 , -0.7592683 , -1.3767385 ,  0.4996251 ,  0.71728456],
       [ 0.10819691,  1.4408439 ,  1.4879323 , -0.19036253, -0.9103441 ],
       [-1.315988  ,  0.90409184,  0.04701529,  0.61258537, -0.8335832 ]],
      dtype=float32)

Two potential troubleshooting areas:

    - you migth need to detach it from the gradient calculation
    - you migth need to pull it out of the GPU
    - for NN computation, you might need to push your data (tensors) to the GPU



# Exercise

**1. Create a tensor of integers in the range 0-100 of size 16x16**

In [3]:
t_exercise = torch.randint(0, 100, (16, 16))
t_exercise

tensor([[ 1, 20, 97, 77, 72, 48,  5, 24, 23, 80, 10, 48, 58, 64, 47,  0],
        [45, 73, 35,  0,  3,  4, 40, 74, 67, 75, 88, 24, 57,  4, 62, 55],
        [97, 94, 73, 45, 32, 41, 93, 75, 36, 57, 53, 32, 92, 92,  7, 60],
        [38, 90, 90, 75, 57, 64, 18, 31, 76, 74, 19, 70, 35, 56, 90, 87],
        [30, 89, 61, 10, 49, 45, 90, 17, 35, 30, 24, 18, 24, 51,  8, 53],
        [32, 40, 97,  7, 51, 55, 12, 92, 85,  7, 84, 71, 19,  4, 67, 87],
        [53, 45, 98, 26, 29,  5, 74, 76, 95, 15, 55, 70, 68, 86, 18,  7],
        [97, 26, 51, 94, 24, 41, 61, 11, 31, 41, 80, 81, 24, 53, 99, 19],
        [75, 29, 29, 85,  9, 23, 34, 97, 35, 10, 44, 83, 63,  9, 25, 57],
        [93, 53, 21, 28, 10, 64, 75, 53, 14, 52,  1, 83, 36, 79, 79, 17],
        [80, 47, 94, 73, 75, 61, 69, 52, 34, 95, 34, 73, 88,  6, 29, 40],
        [30, 82, 46, 32, 71, 42, 93, 31, 13, 43, 38,  6, 67, 90, 60, 23],
        [ 4, 69, 99, 51, 85, 77,  1, 81, 28, 65, 64, 56, 54, 82, 51, 48],
        [40, 43, 98,  2, 11, 53, 99, 6

**2. Change its "gradient-status" by attaching it to gradient calculation**

In [7]:
t_exercise = torch.randint(0, 100, (16, 16), dtype=torch.float, requires_grad=True)
print(t_exercise)

tensor([[16., 29., 66., 35., 47., 30., 49., 55., 16., 49., 45., 15., 28., 43.,
         58., 94.],
        [91., 42., 41.,  6., 95., 38., 94., 48., 84.,  6., 80., 90., 64., 79.,
         58., 10.],
        [ 2., 95., 95.,  9., 82., 37., 36., 50., 76., 65.,  6., 73., 21., 79.,
          6.,  6.],
        [86., 63., 22., 65., 90., 77., 29., 84., 74., 89., 19., 61., 50., 73.,
         24., 60.],
        [52., 55., 96.,  1., 98., 36.,  0., 49., 37., 37., 15., 49., 16., 67.,
         41., 78.],
        [71., 62.,  5., 20., 79., 57., 71., 34., 52., 37., 25., 99., 18., 91.,
         55., 39.],
        [89., 87., 55., 10., 34., 96., 46., 47., 16., 72.,  8., 88., 14.,  2.,
         99., 89.],
        [37., 32., 78., 30., 55., 31., 76., 74., 19., 14., 75.,  1., 72., 90.,
         64., 23.],
        [15., 10., 14., 48., 90., 23.,  0., 13., 91., 56., 97.,  2., 86., 63.,
          1., 70.],
        [98., 77., 61., 57., 43., 30., 48., 19.,  1., 11., 90., 26., 88., 35.,
          7., 21.],
        [9

**Solve the problem appearing in (2.) by creating a float32 tensor and attaching the gradient again**

In [8]:
t_exercise = torch.randint(0, 100, (16, 16), dtype=torch.float32, requires_grad=True)
print(t_exercise)

tensor([[57., 21., 18., 68., 27.,  6., 71.,  5., 86.,  6., 67., 95., 36., 14.,
         38., 44.],
        [16., 34., 41., 98.,  4., 80., 43., 50., 11., 74., 24., 77.,  3., 60.,
         68., 23.],
        [92., 10., 88., 78., 74.,  6., 40., 13., 52., 83., 72., 79., 13., 83.,
         90., 99.],
        [75., 73., 90., 95., 81., 59., 13., 16., 41., 98., 90., 20., 90., 72.,
         10., 64.],
        [97., 30., 62., 56., 45., 93., 99., 20., 78., 98., 48.,  1., 79., 95.,
         66., 99.],
        [10., 57., 97., 22., 54., 15., 36., 92., 28., 97., 41., 60., 54., 64.,
         91., 28.],
        [58., 53., 23., 56., 85., 66., 95., 11., 86., 94., 66., 57., 20., 12.,
         70., 20.],
        [15., 31., 57., 39., 67., 76., 51., 46., 55., 66.,  3., 90., 82., 46.,
         60., 31.],
        [92., 76., 15., 36., 70., 63., 28., 76., 19., 44., 68., 89., 30., 49.,
         22., 63.],
        [80., 55., 61., 76., 42., 70., 35., 32., 84., 44., 20., 52.,  4., 77.,
         77., 81.],
        [8

**Flatten the array to 1d**

In [12]:
flat_tensor = t_exercise.flatten()
flat_tensor

tensor([57., 21., 18., 68., 27.,  6., 71.,  5., 86.,  6., 67., 95., 36., 14.,
        38., 44., 16., 34., 41., 98.,  4., 80., 43., 50., 11., 74., 24., 77.,
         3., 60., 68., 23., 92., 10., 88., 78., 74.,  6., 40., 13., 52., 83.,
        72., 79., 13., 83., 90., 99., 75., 73., 90., 95., 81., 59., 13., 16.,
        41., 98., 90., 20., 90., 72., 10., 64., 97., 30., 62., 56., 45., 93.,
        99., 20., 78., 98., 48.,  1., 79., 95., 66., 99., 10., 57., 97., 22.,
        54., 15., 36., 92., 28., 97., 41., 60., 54., 64., 91., 28., 58., 53.,
        23., 56., 85., 66., 95., 11., 86., 94., 66., 57., 20., 12., 70., 20.,
        15., 31., 57., 39., 67., 76., 51., 46., 55., 66.,  3., 90., 82., 46.,
        60., 31., 92., 76., 15., 36., 70., 63., 28., 76., 19., 44., 68., 89.,
        30., 49., 22., 63., 80., 55., 61., 76., 42., 70., 35., 32., 84., 44.,
        20., 52.,  4., 77., 77., 81., 84., 62., 80.,  1., 80., 75., 62., 25.,
        34., 38., 32., 58., 60., 39., 75., 17., 38., 11., 50., 3

**Transform your flat tensor to a numpy array**

Tensor to Numpy: Detach it from the gradient calculation system to recover it:

In [16]:
numpy_from_tensor = flat_tensor.detach().numpy()
numpy_from_tensor

array([57., 21., 18., 68., 27.,  6., 71.,  5., 86.,  6., 67., 95., 36.,
       14., 38., 44., 16., 34., 41., 98.,  4., 80., 43., 50., 11., 74.,
       24., 77.,  3., 60., 68., 23., 92., 10., 88., 78., 74.,  6., 40.,
       13., 52., 83., 72., 79., 13., 83., 90., 99., 75., 73., 90., 95.,
       81., 59., 13., 16., 41., 98., 90., 20., 90., 72., 10., 64., 97.,
       30., 62., 56., 45., 93., 99., 20., 78., 98., 48.,  1., 79., 95.,
       66., 99., 10., 57., 97., 22., 54., 15., 36., 92., 28., 97., 41.,
       60., 54., 64., 91., 28., 58., 53., 23., 56., 85., 66., 95., 11.,
       86., 94., 66., 57., 20., 12., 70., 20., 15., 31., 57., 39., 67.,
       76., 51., 46., 55., 66.,  3., 90., 82., 46., 60., 31., 92., 76.,
       15., 36., 70., 63., 28., 76., 19., 44., 68., 89., 30., 49., 22.,
       63., 80., 55., 61., 76., 42., 70., 35., 32., 84., 44., 20., 52.,
        4., 77., 77., 81., 84., 62., 80.,  1., 80., 75., 62., 25., 34.,
       38., 32., 58., 60., 39., 75., 17., 38., 11., 50., 31., 24